### ISSUE TITLE
Error in middleware

### ISSUE THREAD

**Issue by deepdil-enfin** [cornflourblue/mean-angular2-registration-login-example#2]
i got error in the middle ware while running node server.js

Error
    at middleware (/home/../Desktop/testApp/server/node_modules/express-jwt/lib/index.js:80:21)

**Comment by SunnyPatel29** [comment]
I am also getting the same error, is there any solution for it. 

Error
    at middleware (D:\practice\server\node_modules\express-jwt\lib\index.js:80:21)
    at D:\practice\server\node_modules\express-unless\index.js:47:5
    at Layer.handle [as handle_request] (D:\practice\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\practice\server\node_modules\express\lib\router\index.js:317:13)
    at D:\practice\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\practice\server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\practice\server\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (D:\practice\server\node_modules\body-parser\lib\types\json.js:103:7)
    at Layer.handle [as handle_request] (D:\practice\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\practice\server\node_modules\express\lib\router\index.js:317:13)

**Comment by nyenloop** [comment]
I also face it when I try to delete some user items,
it just throws on Chrome, Firefox works well:

Error
    at middleware (d:\tmp\mean-test01\server\node_modules\express-jwt\lib\index.js:80:21)
    at d:\tmp\mean-test01\server\node_modules\express-unless\index.js:47:5
    at Layer.handle [as handle_request] (d:\tmp\mean-test01\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\tmp\mean-test01\server\node_modules\express\lib\router\index.js:317:13)
    at d:\tmp\mean-test01\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (d:\tmp\mean-test01\server\node_modules\express\lib\router\index.js:335:12)
    at next (d:\tmp\mean-test01\server\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (d:\tmp\mean-test01\server\node_modules\body-parser\lib\types\json.js:103:7)
    at Layer.handle [as handle_request] (d:\tmp\mean-test01\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\tmp\mean-test01\server\node_modules\express\lib\router\index.js:317:13)
